name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core 3.1.100
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.100
        - name: Build
          run: dotnet build --configuration Release
        - name: Running Tests
          run: dotnet test

  publish:
    name: Publish To NuGet.org
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - name: Setup dotnet 3.1.100
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.100
      # Publish
      - name: Publish if version is updated
        uses: rohith/publish-nuget@v1
        with:
          project_dir: src/ApplicationPipeline
          tag_format: v*
          nuget_key: ${{secrets.NUGET_API_KEY}}
