name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish to nuget.org
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - name: Setup dotnet 3.1.100
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.100

      # Publish
      - name: Publish if version is updated
        uses: rohith/publish-nuget@v1
        with:
          project_dir: src/Pipelines.Http
          tag_format: v*
          nuget_key: ${{secrets.NUGET_API_KEY}}
